version: '3.9'

services:
    fortigate-script:
        image: mcr.microsoft.com/powershell
        volumes:
            - ./UptimeKumaPush.ps1:/UptimeKumaPush.ps1
            - ./UptimeKumaPush.json:/UptimeKumaPush.json
        restart: always
        environment:
            TZ: America/New_York
        entrypoint: /usr/bin/pwsh -File /UptimeKumaPush.ps1
